Update pull_request.yml

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -235,8 +235,7 @@ jobs:
     - name: Checkout the source
       uses: actions/checkout@v4
       with:
-        fetch-depth: 5  # Match the number used for jxl-perfhistory
-        ref: ${{ github.event.pull_request.head.sha }}
+        fetch-depth: 0  # Full history needed for jxl-perfhistory
 
     - name: Install latest rust toolchain
       uses: dtolnay/rust-toolchain@stable
@@ -269,7 +268,7 @@ jobs:
       continue-on-error: true  # Never fail the PR
       run: |
         mkdir -p benchmark-binaries
-        (jxl-perfhistory -r 6 -b benchmark-binarie -g "testimages/*.jxl" -c 0.99 -e 0.03 --ignore-noisy-system || echo "Benchmark failed") > benchmark.txt
+        (jxl-perfhistory -r 5 -b benchmark-binaries -g "testimages/*.jxl" -c 0.99 -e 0.03 --ignore-noisy-system || echo "Benchmark failed") > benchmark.txt
 
     - name: Save PR context
       run: |
